# Bun configuration file
# https://bun.sh/docs/runtime/bunfig

[test]
# Exclude vendored libraries and git submodules from test discovery
# The c-kzg-4844 submodule has its own tests with dependencies we don't need

# Explicitly exclude lib directory containing git submodules
# This prevents bun from discovering and running tests in:
# - lib/c-kzg-4844/bindings/node.js/test/kzg.test.ts (requires glob package)
exclude = [
  "lib/**/*",
  "node_modules/**/*",
]
