import { createTsUpOptions } from "@tevm/tsupconfig";

const baseConfig = createTsUpOptions({
	target: "js",
	entry: [
		"src/index.ts",
		// Core modules
		"src/jsonrpc/index.ts",
		"src/provider/index.ts",
		"src/utils/index.ts",
		"src/native/index.ts",
		// EVM modules (top-level and subpaths used in docs)
		"src/evm/index.ts",
		"src/evm/Frame/index.ts",
		"src/evm/Host/index.ts",
		"src/evm/block/index.ts",
		"src/evm/context/index.ts",
		"src/evm/arithmetic/index.ts",
		"src/evm/bitwise/index.ts",
		"src/evm/comparison/index.ts",
		"src/evm/keccak/index.ts",
		"src/evm/memory/index.ts",
		"src/evm/system/index.ts",
		"src/evm/log/index.ts",
		"src/evm/control/index.ts",
		"src/evm/stack/handlers/index.ts",
		"src/evm/storage/handlers/index.ts",
		"src/evm/precompiles/precompiles.ts",
		"src/evm/precompiles/index.ts",
		// Primitives
		"src/primitives/Abi/index.ts",
		"src/primitives/AccessList/index.ts",
		"src/primitives/Address/index.ts",
		"src/primitives/Address/functional.ts",
		"src/primitives/Authorization/index.ts",
		"src/primitives/Base64/index.ts",
		"src/primitives/BinaryTree/index.ts",
		"src/primitives/Blob/index.ts",
		"src/primitives/BloomFilter/index.ts",
		"src/primitives/Bytecode/index.ts",
		"src/primitives/Chain/index.js",
		"src/primitives/Denomination/index.js",
		"src/primitives/Ens/index.ts",
		"src/primitives/EventLog/index.ts",
		"src/primitives/errors/index.ts",
		"src/primitives/FeeMarket/index.js",
		"src/primitives/GasConstants/index.ts",
		"src/primitives/Hardfork/index.ts",
		"src/primitives/Hash/index.ts",
		"src/primitives/Hex/index.ts",
		// Effect Schema entrypoints
		"src/primitives/Hash/effect.ts",
		"src/primitives/Hex/effect.ts",
		"src/primitives/Uint/effect.ts",
		"src/primitives/Transaction/effect.ts",
		"src/primitives/Signature/effect.ts",
		"src/primitives/Bytecode/effect.ts",
		"src/primitives/Base64/effect.ts",
		"src/primitives/Ens/effect.ts",
		"src/primitives/EventLog/effect.ts",
		"src/primitives/AccessList/effect.ts",
		"src/primitives/Transaction/Authorization/effect.ts",
		"src/primitives/Opcode/index.ts",
		"src/primitives/Rlp/effect.ts",
		"src/primitives/Blob/effect.ts",
		"src/primitives/State/effect.ts",
		"src/primitives/Rlp/index.ts",
		"src/primitives/Signature/index.ts",
		"src/primitives/Siwe/index.ts",
		"src/primitives/State/index.ts",
		"src/primitives/Transaction/index.ts",
		"src/primitives/Uint/index.ts",
		// Crypto
		"src/crypto/Bip39/index.js",
		"src/crypto/Blake2/index.ts",
		"src/crypto/ChaCha20Poly1305/index.ts",
		"src/crypto/Ed25519/index.js",
		"src/crypto/EIP712/index.js",
		"src/crypto/HDWallet/index.ts",
		"src/crypto/Keccak256/index.ts",
		"src/crypto/Keccak256/Keccak256.native.ts",
		"src/crypto/KZG/index.js",
		"src/crypto/P256/index.js",
		"src/crypto/Ripemd160/index.ts",
		"src/crypto/Secp256k1/index.js",
		"src/crypto/SHA256/index.ts",
		// WASM
		"src/wasm/index.ts",
		// Functional API entrypoint
		"src/functional.ts",
		// Streaming primitives
		"src/block/index.ts",
		"src/contract/index.ts",
		"src/transaction/index.ts",
		"src/stream/index.ts",
		// Wallet
		"src/wallet/index.ts",
		"src/wallet/hardware/index.ts",
		// Additional crypto modules
		"src/crypto/AesGcm/index.ts",
		"src/crypto/Bls12381/index.ts",
		"src/crypto/bn254/index.ts",
		"src/crypto/HMAC/index.ts",
		"src/crypto/Keystore/index.ts",
		"src/crypto/ModExp/index.ts",
		"src/crypto/X25519/index.ts",
	],
});

// Mark native FFI modules as external to prevent bundling in WASM/browser contexts
const config = Array.isArray(baseConfig) ? baseConfig : [baseConfig];
export default config.map((c) => ({
	...c,
	external: [...(c.external || []), "ffi-napi", "ref-napi", "ref-struct-di"],
}));
