import { createTsUpOptions } from "@tevm/tsupconfig";

export default createTsUpOptions({
	target: "js",
	entry: [
		"src/index.ts",
		// Primitives
		"src/primitives/Abi/index.ts",
		"src/primitives/AccessList/index.ts",
		"src/primitives/Address/index.ts",
		"src/primitives/Authorization/index.ts",
		"src/primitives/Base64/index.js",
		"src/primitives/BinaryTree/index.js",
		"src/primitives/Blob/index.ts",
		"src/primitives/BloomFilter/index.ts",
		"src/primitives/Bytecode/index.ts",
		"src/primitives/Chain/index.js",
		"src/primitives/Denomination/index.ts",
		"src/primitives/EventLog/index.ts",
		"src/primitives/FeeMarket/index.js",
		"src/primitives/GasConstants/index.ts",
		"src/primitives/Hardfork/index.ts",
		"src/primitives/Hash/index.ts",
		"src/primitives/Hex/index.ts",
		"src/primitives/Opcode/index.ts",
		"src/primitives/Rlp/index.ts",
		"src/primitives/Signature/index.ts",
		"src/primitives/Siwe/index.ts",
		"src/primitives/State/index.ts",
		"src/primitives/Transaction/index.ts",
		"src/primitives/Uint/index.ts",
		// Crypto
		"src/crypto/Bip39/index.js",
		"src/crypto/Blake2/index.js",
		"src/crypto/Ed25519/index.js",
		"src/crypto/EIP712/index.js",
		"src/crypto/HDWallet/index.ts",
		"src/crypto/Keccak256/index.js",
		"src/crypto/KZG/index.js",
		"src/crypto/P256/index.js",
		"src/crypto/Ripemd160/index.js",
		"src/crypto/Secp256k1/index.js",
		"src/crypto/SHA256/index.js",
	],
});
