export { MAX, MIN, ONE, SIZE, ZERO } from "./constants.js";
export type { Uint128Type } from "./Uint128Type.js";
import type { Uint128Type } from "./Uint128Type.js";
export declare const from: (value: bigint | number | string) => Uint128Type;
export declare const fromHex: (hex: string) => Uint128Type;
export declare const fromBigInt: (value: bigint) => Uint128Type;
export declare const fromNumber: (value: number) => Uint128Type;
export declare const fromBytes: (bytes: Uint8Array) => Uint128Type;
export declare const fromAbiEncoded: (bytes: Uint8Array) => Uint128Type;
export declare const tryFrom: (value: bigint | number | string) => Uint128Type | null;
export declare const isValid: (value: bigint | number | string) => boolean;
export declare const toHex: (uint: Uint128Type) => string;
export declare const toBigInt: (uint: Uint128Type) => bigint;
export declare const toNumber: (uint: Uint128Type) => number;
export declare const toBytes: (uint: Uint128Type) => Uint8Array;
export declare const toAbiEncoded: (uint: Uint128Type) => Uint8Array;
export declare const toString: (uint: Uint128Type, radix?: number) => string;
export declare const clone: (uint: Uint128Type) => Uint128Type;
export declare const plus: (uint: Uint128Type, b: Uint128Type) => Uint128Type;
export declare const minus: (uint: Uint128Type, b: Uint128Type) => Uint128Type;
export declare const times: (uint: Uint128Type, b: Uint128Type) => Uint128Type;
export declare const dividedBy: (uint: Uint128Type, b: Uint128Type) => Uint128Type;
export declare const modulo: (uint: Uint128Type, b: Uint128Type) => Uint128Type;
export declare const toPower: (uint: Uint128Type, exponent: Uint128Type) => Uint128Type;
export declare const bitwiseAnd: (uint: Uint128Type, b: Uint128Type) => Uint128Type;
export declare const bitwiseOr: (uint: Uint128Type, b: Uint128Type) => Uint128Type;
export declare const bitwiseXor: (uint: Uint128Type, b: Uint128Type) => Uint128Type;
export declare const bitwiseNot: (uint: Uint128Type) => Uint128Type;
export declare const shiftLeft: (uint: Uint128Type, bits: number) => Uint128Type;
export declare const shiftRight: (uint: Uint128Type, bits: number) => Uint128Type;
export declare const equals: (uint: Uint128Type, b: Uint128Type) => boolean;
export declare const notEquals: (uint: Uint128Type, b: Uint128Type) => boolean;
export declare const lessThan: (uint: Uint128Type, b: Uint128Type) => boolean;
export declare const lessThanOrEqual: (uint: Uint128Type, b: Uint128Type) => boolean;
export declare const greaterThan: (uint: Uint128Type, b: Uint128Type) => boolean;
export declare const greaterThanOrEqual: (uint: Uint128Type, b: Uint128Type) => boolean;
export declare const isZero: (uint: Uint128Type) => boolean;
export declare const minimum: (uint: Uint128Type, b: Uint128Type) => Uint128Type;
export declare const maximum: (uint: Uint128Type, b: Uint128Type) => Uint128Type;
export declare const bitLength: (uint: Uint128Type) => number;
export declare const leadingZeros: (uint: Uint128Type) => number;
export declare const popCount: (uint: Uint128Type) => number;
export declare const sum: (values: Uint128Type[]) => Uint128Type;
export declare const product: (values: Uint128Type[]) => Uint128Type;
export declare const min: (values: Uint128Type[]) => Uint128Type;
export declare const max: (values: Uint128Type[]) => Uint128Type;
export declare const gcd: (a: Uint128Type, b: Uint128Type) => Uint128Type;
export declare const lcm: (a: Uint128Type, b: Uint128Type) => Uint128Type;
export declare const isPowerOf2: (uint: Uint128Type) => boolean;
export declare const BrandedUint128: {
    readonly from: (value: bigint | number | string) => Uint128Type;
    readonly fromHex: (hex: string) => Uint128Type;
    readonly fromBigInt: (value: bigint) => Uint128Type;
    readonly fromNumber: (value: number) => Uint128Type;
    readonly fromBytes: (bytes: Uint8Array) => Uint128Type;
    readonly fromAbiEncoded: (bytes: Uint8Array) => Uint128Type;
    readonly tryFrom: (value: bigint | number | string) => Uint128Type | null;
    readonly isValid: (value: bigint | number | string) => boolean;
    readonly toHex: (uint: Uint128Type) => string;
    readonly toBigInt: (uint: Uint128Type) => bigint;
    readonly toNumber: (uint: Uint128Type) => number;
    readonly toBytes: (uint: Uint128Type) => Uint8Array;
    readonly toAbiEncoded: (uint: Uint128Type) => Uint8Array;
    readonly toString: (uint: Uint128Type, radix?: number) => string;
    readonly clone: (uint: Uint128Type) => Uint128Type;
    readonly plus: (uint: Uint128Type, b: Uint128Type) => Uint128Type;
    readonly minus: (uint: Uint128Type, b: Uint128Type) => Uint128Type;
    readonly times: (uint: Uint128Type, b: Uint128Type) => Uint128Type;
    readonly dividedBy: (uint: Uint128Type, b: Uint128Type) => Uint128Type;
    readonly modulo: (uint: Uint128Type, b: Uint128Type) => Uint128Type;
    readonly toPower: (uint: Uint128Type, exponent: Uint128Type) => Uint128Type;
    readonly bitwiseAnd: (uint: Uint128Type, b: Uint128Type) => Uint128Type;
    readonly bitwiseOr: (uint: Uint128Type, b: Uint128Type) => Uint128Type;
    readonly bitwiseXor: (uint: Uint128Type, b: Uint128Type) => Uint128Type;
    readonly bitwiseNot: (uint: Uint128Type) => Uint128Type;
    readonly shiftLeft: (uint: Uint128Type, bits: number) => Uint128Type;
    readonly shiftRight: (uint: Uint128Type, bits: number) => Uint128Type;
    readonly equals: (uint: Uint128Type, b: Uint128Type) => boolean;
    readonly notEquals: (uint: Uint128Type, b: Uint128Type) => boolean;
    readonly lessThan: (uint: Uint128Type, b: Uint128Type) => boolean;
    readonly lessThanOrEqual: (uint: Uint128Type, b: Uint128Type) => boolean;
    readonly greaterThan: (uint: Uint128Type, b: Uint128Type) => boolean;
    readonly greaterThanOrEqual: (uint: Uint128Type, b: Uint128Type) => boolean;
    readonly isZero: (uint: Uint128Type) => boolean;
    readonly minimum: (uint: Uint128Type, b: Uint128Type) => Uint128Type;
    readonly maximum: (uint: Uint128Type, b: Uint128Type) => Uint128Type;
    readonly bitLength: (uint: Uint128Type) => number;
    readonly leadingZeros: (uint: Uint128Type) => number;
    readonly popCount: (uint: Uint128Type) => number;
    readonly sum: (values: Uint128Type[]) => Uint128Type;
    readonly product: (values: Uint128Type[]) => Uint128Type;
    readonly min: (values: Uint128Type[]) => Uint128Type;
    readonly max: (values: Uint128Type[]) => Uint128Type;
    readonly gcd: (a: Uint128Type, b: Uint128Type) => Uint128Type;
    readonly lcm: (a: Uint128Type, b: Uint128Type) => Uint128Type;
    readonly isPowerOf2: (uint: Uint128Type) => boolean;
    readonly MAX: Uint128Type;
    readonly MIN: Uint128Type;
    readonly ZERO: Uint128Type;
    readonly ONE: Uint128Type;
    readonly SIZE: 16;
};
//# sourceMappingURL=index.d.ts.map