export { abs as _abs, dividedBy as _dividedBy, minus as _minus, modulo as _modulo, negate as _negate, plus as _plus, times as _times, } from "./arithmetic.js";
export { and as _and, not as _not, or as _or, shiftLeft as _shiftLeft, shiftRight as _shiftRight, xor as _xor, } from "./bitwise.js";
export { equals as _equals, greaterThan as _greaterThan, isNegative as _isNegative, isPositive as _isPositive, isZero as _isZero, lessThan as _lessThan, maximum as _maximum, minimum as _minimum, sign as _sign, } from "./comparison.js";
export { toBigint as _toBigint, toBytes as _toBytes, toHex as _toHex, toNumber as _toNumber, toString as _toString, } from "./conversions.js";
export { from, fromBigint, fromBytes, fromHex, fromNumber } from "./from.js";
export type { BrandedInt8 } from "./Int8Type.js";
export { INT8_MAX, INT8_MIN } from "./Int8Type.js";
export { bitLength as _bitLength, isValid, leadingZeros as _leadingZeros, popCount as _popCount, } from "./utilities.js";
import type { BrandedInt8 } from "./Int8Type.js";
export type Int8Input = number | bigint | string | BrandedInt8;
export declare function toNumber(value: Int8Input): number;
export declare function toBigint(value: Int8Input): bigint;
export declare function toHex(value: Int8Input): string;
export declare function toBytes(value: Int8Input): Uint8Array;
export declare function toString(value: Int8Input): string;
export declare function plus(a: Int8Input, b: Int8Input): BrandedInt8;
export declare function minus(a: Int8Input, b: Int8Input): BrandedInt8;
export declare function times(a: Int8Input, b: Int8Input): BrandedInt8;
export declare function dividedBy(a: Int8Input, b: Int8Input): BrandedInt8;
export declare function modulo(a: Int8Input, b: Int8Input): BrandedInt8;
export declare function abs(value: Int8Input): BrandedInt8;
export declare function negate(value: Int8Input): BrandedInt8;
export declare function equals(a: Int8Input, b: Int8Input): boolean;
export declare function lessThan(a: Int8Input, b: Int8Input): boolean;
export declare function greaterThan(a: Int8Input, b: Int8Input): boolean;
export declare function isZero(value: Int8Input): boolean;
export declare function isNegative(value: Int8Input): boolean;
export declare function isPositive(value: Int8Input): boolean;
export declare function minimum(a: Int8Input, b: Int8Input): BrandedInt8;
export declare function maximum(a: Int8Input, b: Int8Input): BrandedInt8;
export declare function sign(value: Int8Input): -1 | 0 | 1;
export declare function and(a: Int8Input, b: Int8Input): BrandedInt8;
export declare function or(a: Int8Input, b: Int8Input): BrandedInt8;
export declare function xor(a: Int8Input, b: Int8Input): BrandedInt8;
export declare function not(value: Int8Input): BrandedInt8;
export declare function shiftLeft(value: Int8Input, shift: number): BrandedInt8;
export declare function shiftRight(value: Int8Input, shift: number): BrandedInt8;
export declare function bitLength(value: Int8Input): number;
export declare function leadingZeros(value: Int8Input): number;
export declare function popCount(value: Int8Input): number;
//# sourceMappingURL=index.d.ts.map