import type { BrandedUint } from "./BrandedUint/BrandedUint.js";
import type { bitLength } from "./BrandedUint/bitLength.js";
import type { bitwiseAnd } from "./BrandedUint/bitwiseAnd.js";
import type { bitwiseNot } from "./BrandedUint/bitwiseNot.js";
import type { bitwiseOr } from "./BrandedUint/bitwiseOr.js";
import type { bitwiseXor } from "./BrandedUint/bitwiseXor.js";
import type { dividedBy } from "./BrandedUint/dividedBy.js";
import type { equals } from "./BrandedUint/equals.js";
import type { greaterThan } from "./BrandedUint/greaterThan.js";
import type { greaterThanOrEqual } from "./BrandedUint/greaterThanOrEqual.js";
import type { isValid } from "./BrandedUint/isValid.js";
import type { isZero } from "./BrandedUint/isZero.js";
import type { leadingZeros } from "./BrandedUint/leadingZeros.js";
import type { lessThan } from "./BrandedUint/lessThan.js";
import type { lessThanOrEqual } from "./BrandedUint/lessThanOrEqual.js";
import type { maximum } from "./BrandedUint/maximum.js";
import type { minimum } from "./BrandedUint/minimum.js";
import type { minus } from "./BrandedUint/minus.js";
import type { modulo } from "./BrandedUint/modulo.js";
import type { notEquals } from "./BrandedUint/notEquals.js";
import type { plus } from "./BrandedUint/plus.js";
import type { popCount } from "./BrandedUint/popCount.js";
import type { shiftLeft } from "./BrandedUint/shiftLeft.js";
import type { shiftRight } from "./BrandedUint/shiftRight.js";
import type { times } from "./BrandedUint/times.js";
import type { toAbiEncoded } from "./BrandedUint/toAbiEncoded.js";
import type { toBigInt } from "./BrandedUint/toBigInt.js";
import type { toBytes } from "./BrandedUint/toBytes.js";
import type { toHex } from "./BrandedUint/toHex.js";
import type { toNumber } from "./BrandedUint/toNumber.js";
import type { toPower } from "./BrandedUint/toPower.js";
import type { toString } from "./BrandedUint/toString.js";
import type { tryFrom } from "./BrandedUint/tryFrom.js";

type UintPrototype = BrandedUint & {
	toHex(): string;
	toBigInt(): bigint;
	toNumber(): number;
	toBytes(): Uint8Array;
	toAbiEncoded(): Uint8Array;
	toString(radix?: number): string;
	plus(other: BrandedUint): BrandedUint;
	minus(other: BrandedUint): BrandedUint;
	times(other: BrandedUint): BrandedUint;
	dividedBy(other: BrandedUint): BrandedUint;
	modulo(other: BrandedUint): BrandedUint;
	toPower(exponent: BrandedUint): BrandedUint;
	bitwiseAnd(other: BrandedUint): BrandedUint;
	bitwiseOr(other: BrandedUint): BrandedUint;
	bitwiseXor(other: BrandedUint): BrandedUint;
	bitwiseNot(): BrandedUint;
	shiftLeft(bits: number): BrandedUint;
	shiftRight(bits: number): BrandedUint;
	equals(other: BrandedUint): boolean;
	notEquals(other: BrandedUint): boolean;
	lessThan(other: BrandedUint): boolean;
	lessThanOrEqual(other: BrandedUint): boolean;
	greaterThan(other: BrandedUint): boolean;
	greaterThanOrEqual(other: BrandedUint): boolean;
	isZero(): boolean;
	minimum(other: BrandedUint): BrandedUint;
	maximum(other: BrandedUint): BrandedUint;
	bitLength(): number;
	leadingZeros(): number;
	popCount(): number;
};

export interface UintConstructor {
	(value: bigint | number | string): BrandedUint;
	prototype: UintPrototype;
	MAX: BrandedUint;
	MIN: BrandedUint;
	ZERO: BrandedUint;
	ONE: BrandedUint;
	SIZE: number;
	from(value: bigint | number | string): BrandedUint;
	fromHex(value: string): BrandedUint;
	fromBigInt(value: bigint): BrandedUint;
	fromNumber(value: number | bigint): BrandedUint;
	fromBytes(value: Uint8Array): BrandedUint;
	fromAbiEncoded(value: Uint8Array): BrandedUint;
	tryFrom: typeof tryFrom;
	isValid: typeof isValid;
	toHex: typeof toHex;
	toBigInt: typeof toBigInt;
	toNumber: typeof toNumber;
	toBytes: typeof toBytes;
	toAbiEncoded: typeof toAbiEncoded;
	toString: typeof toString;
	plus: typeof plus;
	minus: typeof minus;
	times: typeof times;
	dividedBy: typeof dividedBy;
	modulo: typeof modulo;
	toPower: typeof toPower;
	bitwiseAnd: typeof bitwiseAnd;
	bitwiseOr: typeof bitwiseOr;
	bitwiseXor: typeof bitwiseXor;
	bitwiseNot: typeof bitwiseNot;
	shiftLeft: typeof shiftLeft;
	shiftRight: typeof shiftRight;
	equals: typeof equals;
	notEquals: typeof notEquals;
	lessThan: typeof lessThan;
	lessThanOrEqual: typeof lessThanOrEqual;
	greaterThan: typeof greaterThan;
	greaterThanOrEqual: typeof greaterThanOrEqual;
	isZero: typeof isZero;
	minimum: typeof minimum;
	maximum: typeof maximum;
	bitLength: typeof bitLength;
	leadingZeros: typeof leadingZeros;
	popCount: typeof popCount;
}
