import type { BrandedUint } from "./BrandedUint.js";
import type { bitLength } from "./bitLength.js";
import type { bitwiseAnd } from "./bitwiseAnd.js";
import type { bitwiseNot } from "./bitwiseNot.js";
import type { bitwiseOr } from "./bitwiseOr.js";
import type { bitwiseXor } from "./bitwiseXor.js";
import type { dividedBy } from "./dividedBy.js";
import type { equals } from "./equals.js";
import type { greaterThan } from "./greaterThan.js";
import type { greaterThanOrEqual } from "./greaterThanOrEqual.js";
import type { isValid } from "./isValid.js";
import type { isZero } from "./isZero.js";
import type { leadingZeros } from "./leadingZeros.js";
import type { lessThan } from "./lessThan.js";
import type { lessThanOrEqual } from "./lessThanOrEqual.js";
import type { maximum } from "./maximum.js";
import type { minimum } from "./minimum.js";
import type { minus } from "./minus.js";
import type { modulo } from "./modulo.js";
import type { notEquals } from "./notEquals.js";
import type { plus } from "./plus.js";
import type { popCount } from "./popCount.js";
import type { shiftLeft } from "./shiftLeft.js";
import type { shiftRight } from "./shiftRight.js";
import type { times } from "./times.js";
import type { toAbiEncoded } from "./toAbiEncoded.js";
import type { toBigInt } from "./toBigInt.js";
import type { toBytes } from "./toBytes.js";
import type { toHex } from "./toHex.js";
import type { toNumber } from "./toNumber.js";
import type { toPower } from "./toPower.js";
import type { toString } from "./toString.js";
import type { tryFrom } from "./tryFrom.js";

type UintPrototype = BrandedUint & {
	toHex(): string;
	toBigInt(): bigint;
	toNumber(): number;
	toBytes(): Uint8Array;
	toAbiEncoded(): Uint8Array;
	toString(radix?: number): string;
	plus(other: BrandedUint): BrandedUint;
	minus(other: BrandedUint): BrandedUint;
	times(other: BrandedUint): BrandedUint;
	dividedBy(other: BrandedUint): BrandedUint;
	modulo(other: BrandedUint): BrandedUint;
	toPower(exponent: BrandedUint): BrandedUint;
	bitwiseAnd(other: BrandedUint): BrandedUint;
	bitwiseOr(other: BrandedUint): BrandedUint;
	bitwiseXor(other: BrandedUint): BrandedUint;
	bitwiseNot(): BrandedUint;
	shiftLeft(bits: number): BrandedUint;
	shiftRight(bits: number): BrandedUint;
	equals(other: BrandedUint): boolean;
	notEquals(other: BrandedUint): boolean;
	lessThan(other: BrandedUint): boolean;
	lessThanOrEqual(other: BrandedUint): boolean;
	greaterThan(other: BrandedUint): boolean;
	greaterThanOrEqual(other: BrandedUint): boolean;
	isZero(): boolean;
	minimum(other: BrandedUint): BrandedUint;
	maximum(other: BrandedUint): BrandedUint;
	bitLength(): number;
	leadingZeros(): number;
	popCount(): number;
};

export interface UintConstructor {
	(value: bigint | number | string): BrandedUint;
	prototype: UintPrototype;
	MAX: BrandedUint;
	MIN: BrandedUint;
	ZERO: BrandedUint;
	ONE: BrandedUint;
	SIZE: number;
	from(value: bigint | number | string): BrandedUint;
	fromHex(value: string): BrandedUint;
	fromBigInt(value: bigint): BrandedUint;
	fromNumber(value: number | bigint): BrandedUint;
	fromBytes(value: Uint8Array): BrandedUint;
	fromAbiEncoded(value: Uint8Array): BrandedUint;
	tryFrom: typeof tryFrom;
	isValid: typeof isValid;
	toHex: typeof toHex;
	toBigInt: typeof toBigInt;
	toNumber: typeof toNumber;
	toBytes: typeof toBytes;
	toAbiEncoded: typeof toAbiEncoded;
	toString: typeof toString;
	plus: typeof plus;
	minus: typeof minus;
	times: typeof times;
	dividedBy: typeof dividedBy;
	modulo: typeof modulo;
	toPower: typeof toPower;
	bitwiseAnd: typeof bitwiseAnd;
	bitwiseOr: typeof bitwiseOr;
	bitwiseXor: typeof bitwiseXor;
	bitwiseNot: typeof bitwiseNot;
	shiftLeft: typeof shiftLeft;
	shiftRight: typeof shiftRight;
	equals: typeof equals;
	notEquals: typeof notEquals;
	lessThan: typeof lessThan;
	lessThanOrEqual: typeof lessThanOrEqual;
	greaterThan: typeof greaterThan;
	greaterThanOrEqual: typeof greaterThanOrEqual;
	isZero: typeof isZero;
	minimum: typeof minimum;
	maximum: typeof maximum;
	bitLength: typeof bitLength;
	leadingZeros: typeof leadingZeros;
	popCount: typeof popCount;
}
