import type { BrandedUint } from "./BrandedUint.js";
import type { bitLength } from "./bitLength.js";
import type { bitwiseAnd } from "./bitwiseAnd.js";
import type { bitwiseNot } from "./bitwiseNot.js";
import type { bitwiseOr } from "./bitwiseOr.js";
import type { bitwiseXor } from "./bitwiseXor.js";
import type { dividedBy } from "./dividedBy.js";
import type { equals } from "./equals.js";
import type { from } from "./from.js";
import type { fromAbiEncoded } from "./fromAbiEncoded.js";
import type { fromBigInt } from "./fromBigInt.js";
import type { fromBytes } from "./fromBytes.js";
import type { fromHex } from "./fromHex.js";
import type { fromNumber } from "./fromNumber.js";
import type { greaterThan } from "./greaterThan.js";
import type { greaterThanOrEqual } from "./greaterThanOrEqual.js";
import type { isValid } from "./isValid.js";
import type { isZero } from "./isZero.js";
import type { leadingZeros } from "./leadingZeros.js";
import type { lessThan } from "./lessThan.js";
import type { lessThanOrEqual } from "./lessThanOrEqual.js";
import type { maximum } from "./maximum.js";
import type { minimum } from "./minimum.js";
import type { minus } from "./minus.js";
import type { modulo } from "./modulo.js";
import type { notEquals } from "./notEquals.js";
import type { plus } from "./plus.js";
import type { popCount } from "./popCount.js";
import type { shiftLeft } from "./shiftLeft.js";
import type { shiftRight } from "./shiftRight.js";
import type { times } from "./times.js";
import type { toAbiEncoded } from "./toAbiEncoded.js";
import type { toBigInt } from "./toBigInt.js";
import type { toBytes } from "./toBytes.js";
import type { toHex } from "./toHex.js";
import type { toNumber } from "./toNumber.js";
import type { toPower } from "./toPower.js";
import type { toString } from "./toString.js";
import type { tryFrom } from "./tryFrom.js";

type UintPrototype = BrandedUint & {
	toHex: typeof toHex;
	toBigInt: typeof toBigInt;
	toNumber: typeof toNumber;
	toBytes: typeof toBytes;
	toAbiEncoded: typeof toAbiEncoded;
	toString: typeof toString;
	plus: typeof plus;
	minus: typeof minus;
	times: typeof times;
	dividedBy: typeof dividedBy;
	modulo: typeof modulo;
	toPower: typeof toPower;
	bitwiseAnd: typeof bitwiseAnd;
	bitwiseOr: typeof bitwiseOr;
	bitwiseXor: typeof bitwiseXor;
	bitwiseNot: typeof bitwiseNot;
	shiftLeft: typeof shiftLeft;
	shiftRight: typeof shiftRight;
	equals: typeof equals;
	notEquals: typeof notEquals;
	lessThan: typeof lessThan;
	lessThanOrEqual: typeof lessThanOrEqual;
	greaterThan: typeof greaterThan;
	greaterThanOrEqual: typeof greaterThanOrEqual;
	isZero: typeof isZero;
	minimum: typeof minimum;
	maximum: typeof maximum;
	bitLength: typeof bitLength;
	leadingZeros: typeof leadingZeros;
	popCount: typeof popCount;
};

export interface UintConstructor {
	(value: bigint | number | string): BrandedUint;
	prototype: UintPrototype;
	from: typeof from;
	fromHex: typeof fromHex;
	fromBigInt: typeof fromBigInt;
	fromNumber: typeof fromNumber;
	fromBytes: typeof fromBytes;
	fromAbiEncoded: typeof fromAbiEncoded;
	tryFrom: typeof tryFrom;
	isValid: typeof isValid;
	toHex: typeof toHex;
	toBigInt: typeof toBigInt;
	toNumber: typeof toNumber;
	toBytes: typeof toBytes;
	toAbiEncoded: typeof toAbiEncoded;
	toString: typeof toString;
	plus: typeof plus;
	minus: typeof minus;
	times: typeof times;
	dividedBy: typeof dividedBy;
	modulo: typeof modulo;
	toPower: typeof toPower;
	bitwiseAnd: typeof bitwiseAnd;
	bitwiseOr: typeof bitwiseOr;
	bitwiseXor: typeof bitwiseXor;
	bitwiseNot: typeof bitwiseNot;
	shiftLeft: typeof shiftLeft;
	shiftRight: typeof shiftRight;
	equals: typeof equals;
	notEquals: typeof notEquals;
	lessThan: typeof lessThan;
	lessThanOrEqual: typeof lessThanOrEqual;
	greaterThan: typeof greaterThan;
	greaterThanOrEqual: typeof greaterThanOrEqual;
	isZero: typeof isZero;
	minimum: typeof minimum;
	maximum: typeof maximum;
	bitLength: typeof bitLength;
	leadingZeros: typeof leadingZeros;
	popCount: typeof popCount;
}
