import { defineConfig } from "vitest/config";

export default defineConfig({
	test: {
		include: ["src/**/*.{test,spec}.{js,ts}"],
		exclude: [
			"**/node_modules/**",
			"src/crypto/Signers/Signers.test.ts",
			// Exclude tests that require native FFI bindings (ref-napi)
			"src/crypto/HDWallet/HDWallet.test.ts",
			"src/crypto/EIP712/EIP712.test.ts",
			"src/primitives/PrivateKey/PrivateKey.test.ts",
			"src/primitives/PublicKey/PublicKey.test.ts",
			"src/primitives/ContractCode/ContractCode.test.ts",
			"src/primitives/InitCode/InitCode.test.ts",
			"src/services/Account/Account.test.ts",
			"src/services/Account/fromMnemonic.test.ts",
			"src/services/Contract/Contract.test.ts",
			"src/services/Signer/Signer.test.ts",
			"src/services/Signer/actions/deployContract.test.ts",
			"src/services/Signer/actions/writeContract.test.ts",
			// Exclude tests with BrandedAbi/voltaire vitest SSR issues
			"src/services/Provider/actions/simulateContract.test.ts",
			"src/services/Provider/actions/readContract.test.ts",
			"src/services/Provider/actions/multicall.test.ts",
			"src/services/Multicall/Multicall.test.ts",
			"src/services/AbiEncoder/AbiEncoder.test.ts",
			"src/primitives/Abi/Abi.test.ts",
			"src/services/Provider/Provider.test.ts",
			"src/services/RawProvider/RawProvider.test.ts",
			"src/services/RpcBatch/RpcBatch.test.ts",
			"src/services/Transport/Transport.test.ts",
			"src/crypto/Secp256k1/Secp256k1.test.ts",
			"src/crypto/Bls12381/Bls12381.test.ts",
			"src/crypto/HMAC/HMAC.test.ts",
			"src/contract/EventStream.test.ts",
			"src/transaction/TransactionStream.test.ts",
			// Exclude tests that require WASM module (crypto/hashing)
			"src/crypto/AesGcm/AesGcm.test.ts",
			"src/crypto/Bip39/Bip39.test.ts",
			"src/crypto/Blake2/Blake2.test.ts",
			"src/crypto/Bn254/Bn254.test.ts",
			"src/crypto/ChaCha20Poly1305/ChaCha20Poly1305.test.ts",
			"src/crypto/KZG/KZG.test.ts",
			"src/crypto/Keccak256/Keccak256.test.ts",
			"src/crypto/ModExp/ModExp.test.ts",
			"src/crypto/Ripemd160/Ripemd160.test.ts",
			"src/crypto/SHA256/SHA256.test.ts",
			"src/crypto/Signature/Signature.test.ts",
			"src/crypto/CryptoLive.test.ts",
			"src/primitives/Address/Address.test.ts",
			"src/primitives/Block/Block.test.ts",
			"src/primitives/BlockBody/BlockBody.test.ts",
			"src/primitives/BlockNumber/BlockNumber.test.ts",
			"src/primitives/ContractSignature/ContractSignature.test.ts",
			"src/primitives/DomainSeparator/DomainSeparator.test.ts",
			"src/primitives/ErrorSignature/ErrorSignature.test.ts",
			"src/primitives/EventSignature/EventSignature.test.ts",
			"src/primitives/FunctionSignature/FunctionSignature.test.ts",
			"src/primitives/PackedUserOperation/hash.test.ts",
			"src/primitives/Receipt/ReceiptSchema.test.ts",
			"src/primitives/ReturnData/ReturnData.test.ts",
			"src/primitives/RevertReason/RevertReason.test.ts",
			"src/primitives/RuntimeCode/RuntimeCode.test.ts",
			"src/primitives/Selector/Selector.test.ts",
			"src/primitives/Siwe/Siwe.test.ts",
			"src/auth/siwe.test.ts",
			"src/standards/ERC165.test.ts",
			"src/services/RpcBatch/RpcResolver.test.ts",
		],
		environment: "node",
		setupFiles: ["./vitest.setup.ts"],
	},
});
