/**
 * ERC-5564 Stealth Address Types
 *
 * Branded types for stealth address cryptography using SECP256k1.
 * Enables privacy-preserving transactions through non-interactive address generation.
 *
 * @see https://eips.ethereum.org/EIPS/eip-5564 for ERC-5564 specification
 * @see https://voltaire.tevm.sh/primitives/stealth-address for StealthAddress documentation
 * @since 0.0.0
 */
import type { AddressType } from "../Address/AddressType.js";
/**
 * Stealth meta-address (66 bytes)
 *
 * Concatenation of spending public key (33 bytes compressed) and
 * viewing public key (33 bytes compressed). Published by recipient
 * to enable non-interactive stealth address generation.
 *
 * Format: spendingPubKey (33) || viewingPubKey (33)
 *
 * @see https://eips.ethereum.org/EIPS/eip-5564#stealth-meta-address-format
 */
export type StealthMetaAddress = Uint8Array & {
    readonly __tag: "StealthMetaAddress";
};
/**
 * Spending public key (33 bytes compressed)
 *
 * Compressed secp256k1 public key used for deriving stealth addresses.
 * Recipient uses corresponding private key to spend from stealth addresses.
 */
export type SpendingPublicKey = Uint8Array & {
    readonly __tag: "SpendingPublicKey";
};
/**
 * Viewing public key (33 bytes compressed)
 *
 * Compressed secp256k1 public key used for scanning blockchain.
 * Recipient uses corresponding private key to detect stealth addresses.
 */
export type ViewingPublicKey = Uint8Array & {
    readonly __tag: "ViewingPublicKey";
};
/**
 * Ephemeral public key (33 bytes compressed)
 *
 * One-time public key generated by sender and announced on-chain.
 * Used by recipient to derive shared secret for stealth address detection.
 */
export type EphemeralPublicKey = Uint8Array & {
    readonly __tag: "EphemeralPublicKey";
};
/**
 * View tag (1 byte)
 *
 * First byte of hashed shared secret. Enables fast rejection
 * of non-matching stealth addresses (~255/256 probability).
 * Reduces scanning overhead by ~6x.
 */
export type ViewTag = number;
/**
 * Stealth address announcement
 *
 * On-chain data published by sender containing ephemeral public key
 * and view tag. Enables recipient to scan for stealth addresses.
 */
export interface StealthAnnouncement {
    ephemeralPublicKey: EphemeralPublicKey;
    viewTag: ViewTag;
    stealthAddress: AddressType;
}
/**
 * Result of stealth address generation
 */
export interface GenerateStealthAddressResult {
    stealthAddress: AddressType;
    ephemeralPublicKey: EphemeralPublicKey;
    viewTag: ViewTag;
}
/**
 * Result of stealth address checking
 */
export interface CheckStealthAddressResult {
    isForRecipient: boolean;
    stealthPrivateKey?: Uint8Array;
}
//# sourceMappingURL=StealthAddressType.d.ts.map