export * from "./constants.js";
export * from "./errors.js";
export * from "./Secp256k1PublicKeyType.js";
export * from "./SignatureType.js";
export const Signature: typeof SignatureMethods;
export const PublicKey: typeof PublicKeyMethods;
export const PrivateKey: typeof PrivateKeyMethods;
export namespace Secp256k1 {
    export { sign };
    export { signHash };
    export { verify };
    export { verifyHash };
    export { recoverPublicKey };
    export { recoverPublicKeyFromHash };
    export { derivePublicKey };
    export { isValidSignature };
    export { isValidPublicKey };
    export { isValidPrivateKey };
    export { randomPrivateKey };
    export { createKeyPair };
    export { ecdh };
    export { ecdh as getSharedSecret };
    export { addPoints };
    export { scalarMultiply };
    export { SignatureMethods as Signature };
    export { PublicKeyMethods as PublicKey };
    export { PrivateKeyMethods as PrivateKey };
    export { CURVE_ORDER };
    export { PRIVATE_KEY_SIZE };
    export { PUBLIC_KEY_SIZE };
    export { SIGNATURE_COMPONENT_SIZE };
}
export type Secp256k1SignatureType = import("./SignatureType.js").Secp256k1SignatureType;
import { sign } from "./sign.js";
import { signHash } from "./signHash.js";
import { verify } from "./verify.js";
import { verifyHash } from "./verifyHash.js";
import { recoverPublicKey } from "./recoverPublicKey.js";
import { recoverPublicKeyFromHash } from "./recoverPublicKeyFromHash.js";
import { derivePublicKey } from "./derivePublicKey.js";
import { isValidSignature } from "./isValidSignature.js";
import { isValidPublicKey } from "./isValidPublicKey.js";
import { isValidPrivateKey } from "./isValidPrivateKey.js";
import { randomPrivateKey } from "./randomPrivateKey.js";
import { createKeyPair } from "./createKeyPair.js";
import { ecdh } from "./ecdh.js";
import { addPoints } from "./addPoints.js";
import { scalarMultiply } from "./scalarMultiply.js";
import * as SignatureMethods from "./Signature/index.js";
import * as PublicKeyMethods from "./PublicKey/index.js";
import * as PrivateKeyMethods from "../../primitives/PrivateKey/index.js";
import { CURVE_ORDER } from "./constants.js";
import { PRIVATE_KEY_SIZE } from "./constants.js";
import { PUBLIC_KEY_SIZE } from "./constants.js";
import { SIGNATURE_COMPONENT_SIZE } from "./constants.js";
export { sign, signHash, verify, verifyHash, recoverPublicKey, recoverPublicKeyFromHash, derivePublicKey, isValidSignature, isValidPublicKey, isValidPrivateKey, randomPrivateKey, createKeyPair, ecdh, ecdh as getSharedSecret, addPoints, scalarMultiply };
//# sourceMappingURL=Secp256k1.d.ts.map