export * from "./constants.js";
export * from "./Uint16Type.js";
import { bitLength } from "./bitLength.js";
import { bitwiseAnd } from "./bitwiseAnd.js";
import { bitwiseNot } from "./bitwiseNot.js";
import { bitwiseOr } from "./bitwiseOr.js";
import { bitwiseXor } from "./bitwiseXor.js";
import { dividedBy } from "./dividedBy.js";
import { equals } from "./equals.js";
import { from } from "./from.js";
import { fromBigint } from "./fromBigint.js";
import { fromBytes } from "./fromBytes.js";
import { fromHex } from "./fromHex.js";
import { fromNumber } from "./fromNumber.js";
import { greaterThan } from "./greaterThan.js";
import { isValid } from "./isValid.js";
import { isZero } from "./isZero.js";
import { leadingZeros } from "./leadingZeros.js";
import { lessThan } from "./lessThan.js";
import { maximum } from "./maximum.js";
import { minimum } from "./minimum.js";
import { minus } from "./minus.js";
import { modulo } from "./modulo.js";
import { plus } from "./plus.js";
import { popCount } from "./popCount.js";
import { shiftLeft } from "./shiftLeft.js";
import { shiftRight } from "./shiftRight.js";
import { times } from "./times.js";
import { toBigint } from "./toBigint.js";
import { toBytes } from "./toBytes.js";
import { toHex } from "./toHex.js";
import { toNumber } from "./toNumber.js";
import { toString } from "./toString.js";
export { from, fromHex, fromBigint, fromNumber, fromBytes, isValid, toHex, toBigint, toNumber, toBytes, toString, plus, minus, times, dividedBy, modulo, bitwiseAnd, bitwiseOr, bitwiseXor, bitwiseNot, shiftLeft, shiftRight, equals, lessThan, greaterThan, isZero, minimum, maximum, bitLength, leadingZeros, popCount, };
export declare const Uint16Type: {
    from: typeof from;
    fromHex: typeof fromHex;
    fromBigint: typeof fromBigint;
    fromNumber: typeof fromNumber;
    fromBytes: typeof fromBytes;
    isValid: typeof isValid;
    toHex: typeof toHex;
    toBigint: typeof toBigint;
    toNumber: typeof toNumber;
    toBytes: typeof toBytes;
    toString: typeof toString;
    plus: typeof plus;
    minus: typeof minus;
    times: typeof times;
    dividedBy: typeof dividedBy;
    modulo: typeof modulo;
    bitwiseAnd: typeof bitwiseAnd;
    bitwiseOr: typeof bitwiseOr;
    bitwiseXor: typeof bitwiseXor;
    bitwiseNot: typeof bitwiseNot;
    shiftLeft: typeof shiftLeft;
    shiftRight: typeof shiftRight;
    equals: typeof equals;
    lessThan: typeof lessThan;
    greaterThan: typeof greaterThan;
    isZero: typeof isZero;
    minimum: typeof minimum;
    maximum: typeof maximum;
    bitLength: typeof bitLength;
    leadingZeros: typeof leadingZeros;
    popCount: typeof popCount;
    MAX: import("./Uint16Type.js").Uint16Type;
    MIN: import("./Uint16Type.js").Uint16Type;
    ZERO: import("./Uint16Type.js").Uint16Type;
    ONE: import("./Uint16Type.js").Uint16Type;
    SIZE: number;
};
//# sourceMappingURL=index.d.ts.map