import type { bitLength } from "./bitLength.js";
import type { bitwiseAnd } from "./bitwiseAnd.js";
import type { bitwiseNot } from "./bitwiseNot.js";
import type { bitwiseOr } from "./bitwiseOr.js";
import type { bitwiseXor } from "./bitwiseXor.js";
import type { dividedBy } from "./dividedBy.js";
import type { equals } from "./equals.js";
import type { greaterThan } from "./greaterThan.js";
import type { greaterThanOrEqual } from "./greaterThanOrEqual.js";
import type { isValid } from "./isValid.js";
import type { isZero } from "./isZero.js";
import type { leadingZeros } from "./leadingZeros.js";
import type { lessThan } from "./lessThan.js";
import type { lessThanOrEqual } from "./lessThanOrEqual.js";
import type { maximum } from "./maximum.js";
import type { minimum } from "./minimum.js";
import type { minus } from "./minus.js";
import type { modulo } from "./modulo.js";
import type { notEquals } from "./notEquals.js";
import type { plus } from "./plus.js";
import type { popCount } from "./popCount.js";
import type { shiftLeft } from "./shiftLeft.js";
import type { shiftRight } from "./shiftRight.js";
import type { times } from "./times.js";
import type { toAbiEncoded } from "./toAbiEncoded.js";
import type { toBigInt } from "./toBigInt.js";
import type { toBytes } from "./toBytes.js";
import type { toHex } from "./toHex.js";
import type { toNumber } from "./toNumber.js";
import type { toPower } from "./toPower.js";
import type { toString } from "./toString.js";
import type { tryFrom } from "./tryFrom.js";
import type { Uint256Type } from "./Uint256Type.js";
type UintPrototype = Uint256Type & {
    toHex(): string;
    toBigInt(): bigint;
    toNumber(): number;
    toBytes(): Uint8Array;
    toAbiEncoded(): Uint8Array;
    toString(radix?: number): string;
    plus(other: Uint256Type): Uint256Type;
    minus(other: Uint256Type): Uint256Type;
    times(other: Uint256Type): Uint256Type;
    dividedBy(other: Uint256Type): Uint256Type;
    modulo(other: Uint256Type): Uint256Type;
    toPower(exponent: Uint256Type): Uint256Type;
    bitwiseAnd(other: Uint256Type): Uint256Type;
    bitwiseOr(other: Uint256Type): Uint256Type;
    bitwiseXor(other: Uint256Type): Uint256Type;
    bitwiseNot(): Uint256Type;
    shiftLeft(bits: number): Uint256Type;
    shiftRight(bits: number): Uint256Type;
    equals(other: Uint256Type): boolean;
    notEquals(other: Uint256Type): boolean;
    lessThan(other: Uint256Type): boolean;
    lessThanOrEqual(other: Uint256Type): boolean;
    greaterThan(other: Uint256Type): boolean;
    greaterThanOrEqual(other: Uint256Type): boolean;
    isZero(): boolean;
    minimum(other: Uint256Type): Uint256Type;
    maximum(other: Uint256Type): Uint256Type;
    bitLength(): number;
    leadingZeros(): number;
    popCount(): number;
};
export interface UintConstructor {
    (value: bigint | number | string): Uint256Type;
    prototype: UintPrototype;
    MAX: Uint256Type;
    MIN: Uint256Type;
    ZERO: Uint256Type;
    ONE: Uint256Type;
    SIZE: number;
    from(value: bigint | number | string): Uint256Type;
    fromHex(value: string): Uint256Type;
    fromBigInt(value: bigint): Uint256Type;
    fromNumber(value: number | bigint): Uint256Type;
    fromBytes(value: Uint8Array): Uint256Type;
    fromAbiEncoded(value: Uint8Array): Uint256Type;
    tryFrom: typeof tryFrom;
    isValid: typeof isValid;
    toHex: typeof toHex;
    toBigInt: typeof toBigInt;
    toNumber: typeof toNumber;
    toBytes: typeof toBytes;
    toAbiEncoded: typeof toAbiEncoded;
    toString: typeof toString;
    plus: typeof plus;
    minus: typeof minus;
    times: typeof times;
    dividedBy: typeof dividedBy;
    modulo: typeof modulo;
    toPower: typeof toPower;
    bitwiseAnd: typeof bitwiseAnd;
    bitwiseOr: typeof bitwiseOr;
    bitwiseXor: typeof bitwiseXor;
    bitwiseNot: typeof bitwiseNot;
    shiftLeft: typeof shiftLeft;
    shiftRight: typeof shiftRight;
    equals: typeof equals;
    notEquals: typeof notEquals;
    lessThan: typeof lessThan;
    lessThanOrEqual: typeof lessThanOrEqual;
    greaterThan: typeof greaterThan;
    greaterThanOrEqual: typeof greaterThanOrEqual;
    isZero: typeof isZero;
    minimum: typeof minimum;
    maximum: typeof maximum;
    bitLength: typeof bitLength;
    leadingZeros: typeof leadingZeros;
    popCount: typeof popCount;
}
export {};
//# sourceMappingURL=UintConstructor.d.ts.map