import type { Address } from "../Address/index.js";
import type { Hash } from "../Hash/index.js";
import type { BrandedAccessList, Item } from "./BrandedAccessList.js";
import type { addressCount } from "./addressCount.js";
import type { assertValid } from "./assertValid.js";
import type { create } from "./create.js";
import type { deduplicate } from "./deduplicate.js";
import type { from } from "./from.js";
import type { fromBytes } from "./fromBytes.js";
import type { gasCost } from "./gasCost.js";
import type { gasSavings } from "./gasSavings.js";
import type { hasSavings } from "./hasSavings.js";
import type { includesAddress } from "./includesAddress.js";
import type { includesStorageKey } from "./includesStorageKey.js";
import type { is } from "./is.js";
import type { isEmpty } from "./isEmpty.js";
import type { isItem } from "./isItem.js";
import type { keysFor } from "./keysFor.js";
import type { merge } from "./merge.js";
import type { storageKeyCount } from "./storageKeyCount.js";
import type { toBytes } from "./toBytes.js";
import type { withAddress } from "./withAddress.js";
import type { withStorageKey } from "./withStorageKey.js";

type AccessListPrototype = BrandedAccessList & {
	gasCost: typeof gasCost;
	gasSavings: typeof gasSavings;
	hasSavings: typeof hasSavings;
	includesAddress: typeof includesAddress;
	includesStorageKey: typeof includesStorageKey;
	keysFor: typeof keysFor;
	deduplicate: typeof deduplicate;
	withAddress: typeof withAddress;
	withStorageKey: typeof withStorageKey;
	assertValid: typeof assertValid;
	toBytes: typeof toBytes;
	addressCount: typeof addressCount;
	storageKeyCount: typeof storageKeyCount;
	isEmpty: typeof isEmpty;
};

export interface AccessListConstructor {
	(value: readonly Item[] | Uint8Array): AccessListPrototype;
	prototype: AccessListPrototype;
	from(value: readonly Item[] | Uint8Array): AccessListPrototype;
	fromBytes(value: Uint8Array): AccessListPrototype;
	is: typeof is;
	isItem: typeof isItem;
	create: typeof create;
	merge: typeof merge;
	gasCost: typeof gasCost;
	gasSavings: typeof gasSavings;
	hasSavings: typeof hasSavings;
	includesAddress: typeof includesAddress;
	includesStorageKey: typeof includesStorageKey;
	keysFor: typeof keysFor;
	deduplicate: typeof deduplicate;
	withAddress: typeof withAddress;
	withStorageKey: typeof withStorageKey;
	assertValid: typeof assertValid;
	toBytes: typeof toBytes;
	addressCount: typeof addressCount;
	storageKeyCount: typeof storageKeyCount;
	isEmpty: typeof isEmpty;
	ADDRESS_COST: bigint;
	STORAGE_KEY_COST: bigint;
	COLD_ACCOUNT_ACCESS_COST: bigint;
	COLD_STORAGE_ACCESS_COST: bigint;
	WARM_STORAGE_ACCESS_COST: bigint;
}
