import type { HexType } from "./HexType/HexType.js";
import type { assertSize } from "./HexType/assertSize.js";
import type { concat } from "./HexType/concat.js";
import type { equals } from "./HexType/equals.js";
import type { from } from "./HexType/from.js";
import type { fromBigInt } from "./HexType/fromBigInt.js";
import type { fromBoolean } from "./HexType/fromBoolean.js";
import type { fromBytes } from "./HexType/fromBytes.js";
import type { fromNumber } from "./HexType/fromNumber.js";
import type { fromString } from "./HexType/fromString.js";
import type { isHex } from "./HexType/isHex.js";
import type { isSized } from "./HexType/isSized.js";
import type { pad } from "./HexType/pad.js";
import type { padRight } from "./HexType/padRight.js";
import type { random } from "./HexType/random.js";
import type { size } from "./HexType/size.js";
import type { slice } from "./HexType/slice.js";
import type { toBigInt } from "./HexType/toBigInt.js";
import type { toBoolean } from "./HexType/toBoolean.js";
import type { toBytes } from "./HexType/toBytes.js";
import type { toNumber } from "./HexType/toNumber.js";
import type { toString } from "./HexType/toString.js";
import type { trim } from "./HexType/trim.js";
import type { validate } from "./HexType/validate.js";
import type { xor } from "./HexType/xor.js";
import type { zero } from "./HexType/zero.js";

type HexPrototype = HexType & {
	toBytes: typeof toBytes;
	toNumber: typeof toNumber;
	toBigInt: typeof toBigInt;
	toString: typeof toString;
	toBoolean: typeof toBoolean;
	size: typeof size;
	isSized: typeof isSized;
	validate: typeof validate;
	assertSize: typeof assertSize;
	slice: typeof slice;
	pad: typeof pad;
	padRight: typeof padRight;
	trim: typeof trim;
	equals: typeof equals;
	xor: typeof xor;
};

export interface HexConstructor {
	(value: string | Uint8Array): HexType;
	prototype: HexPrototype;
	from: typeof from;
	fromBytes: typeof fromBytes;
	fromNumber: typeof fromNumber;
	fromBigInt: typeof fromBigInt;
	fromString: typeof fromString;
	fromBoolean: typeof fromBoolean;
	isHex: typeof isHex;
	concat: typeof concat;
	random: typeof random;
	zero: typeof zero;
	validate: typeof validate;
	toBytes: typeof toBytes;
	toNumber: typeof toNumber;
	toBigInt: typeof toBigInt;
	toString: typeof toString;
	toBoolean: typeof toBoolean;
	size: typeof size;
	isSized: typeof isSized;
	assertSize: typeof assertSize;
	slice: typeof slice;
	pad: typeof pad;
	padRight: typeof padRight;
	trim: typeof trim;
	equals: typeof equals;
	xor: typeof xor;
}
