import type { BrandedHex } from "./BrandedHex.js";
import type { assertSize } from "./assertSize.js";
import type { concat } from "./concat.js";
import type { equals } from "./equals.js";
import type { from } from "./from.js";
import type { fromBigInt } from "./fromBigInt.js";
import type { fromBoolean } from "./fromBoolean.js";
import type { fromBytes } from "./fromBytes.js";
import type { fromNumber } from "./fromNumber.js";
import type { fromString } from "./fromString.js";
import type { isHex } from "./isHex.js";
import type { isSized } from "./isSized.js";
import type { pad } from "./pad.js";
import type { padRight } from "./padRight.js";
import type { random } from "./random.js";
import type { size } from "./size.js";
import type { slice } from "./slice.js";
import type { toBigInt } from "./toBigInt.js";
import type { toBoolean } from "./toBoolean.js";
import type { toBytes } from "./toBytes.js";
import type { toNumber } from "./toNumber.js";
import type { toString } from "./toString.js";
import type { trim } from "./trim.js";
import type { validate } from "./validate.js";
import type { xor } from "./xor.js";
import type { zero } from "./zero.js";

type HexPrototype = BrandedHex & {
	toBytes: typeof toBytes;
	toNumber: typeof toNumber;
	toBigInt: typeof toBigInt;
	toString: typeof toString;
	toBoolean: typeof toBoolean;
	size: typeof size;
	isSized: typeof isSized;
	validate: typeof validate;
	assertSize: typeof assertSize;
	slice: typeof slice;
	pad: typeof pad;
	padRight: typeof padRight;
	trim: typeof trim;
	equals: typeof equals;
	xor: typeof xor;
};

export interface HexConstructor {
	(value: string | Uint8Array): BrandedHex;
	prototype: HexPrototype;
	from: typeof from;
	fromBytes: typeof fromBytes;
	fromNumber: typeof fromNumber;
	fromBigInt: typeof fromBigInt;
	fromString: typeof fromString;
	fromBoolean: typeof fromBoolean;
	isHex: typeof isHex;
	concat: typeof concat;
	random: typeof random;
	zero: typeof zero;
	validate: typeof validate;
	toBytes: typeof toBytes;
	toNumber: typeof toNumber;
	toBigInt: typeof toBigInt;
	toString: typeof toString;
	toBoolean: typeof toBoolean;
	size: typeof size;
	isSized: typeof isSized;
	assertSize: typeof assertSize;
	slice: typeof slice;
	pad: typeof pad;
	padRight: typeof padRight;
	trim: typeof trim;
	equals: typeof equals;
	xor: typeof xor;
}
