import type { BrandedHex } from "./BrandedHex/BrandedHex.js";
import type { assertSize } from "./BrandedHex/assertSize.js";
import type { concat } from "./BrandedHex/concat.js";
import type { equals } from "./BrandedHex/equals.js";
import type { from } from "./BrandedHex/from.js";
import type { fromBigInt } from "./BrandedHex/fromBigInt.js";
import type { fromBoolean } from "./BrandedHex/fromBoolean.js";
import type { fromBytes } from "./BrandedHex/fromBytes.js";
import type { fromNumber } from "./BrandedHex/fromNumber.js";
import type { fromString } from "./BrandedHex/fromString.js";
import type { isHex } from "./BrandedHex/isHex.js";
import type { isSized } from "./BrandedHex/isSized.js";
import type { pad } from "./BrandedHex/pad.js";
import type { padRight } from "./BrandedHex/padRight.js";
import type { random } from "./BrandedHex/random.js";
import type { size } from "./BrandedHex/size.js";
import type { slice } from "./BrandedHex/slice.js";
import type { toBigInt } from "./BrandedHex/toBigInt.js";
import type { toBoolean } from "./BrandedHex/toBoolean.js";
import type { toBytes } from "./BrandedHex/toBytes.js";
import type { toNumber } from "./BrandedHex/toNumber.js";
import type { toString } from "./BrandedHex/toString.js";
import type { trim } from "./BrandedHex/trim.js";
import type { validate } from "./BrandedHex/validate.js";
import type { xor } from "./BrandedHex/xor.js";
import type { zero } from "./BrandedHex/zero.js";

type HexPrototype = BrandedHex & {
	toBytes: typeof toBytes;
	toNumber: typeof toNumber;
	toBigInt: typeof toBigInt;
	toString: typeof toString;
	toBoolean: typeof toBoolean;
	size: typeof size;
	isSized: typeof isSized;
	validate: typeof validate;
	assertSize: typeof assertSize;
	slice: typeof slice;
	pad: typeof pad;
	padRight: typeof padRight;
	trim: typeof trim;
	equals: typeof equals;
	xor: typeof xor;
};

export interface HexConstructor {
	(value: string | Uint8Array): BrandedHex;
	prototype: HexPrototype;
	from: typeof from;
	fromBytes: typeof fromBytes;
	fromNumber: typeof fromNumber;
	fromBigInt: typeof fromBigInt;
	fromString: typeof fromString;
	fromBoolean: typeof fromBoolean;
	isHex: typeof isHex;
	concat: typeof concat;
	random: typeof random;
	zero: typeof zero;
	validate: typeof validate;
	toBytes: typeof toBytes;
	toNumber: typeof toNumber;
	toBigInt: typeof toBigInt;
	toString: typeof toString;
	toBoolean: typeof toBoolean;
	size: typeof size;
	isSized: typeof isSized;
	assertSize: typeof assertSize;
	slice: typeof slice;
	pad: typeof pad;
	padRight: typeof padRight;
	trim: typeof trim;
	equals: typeof equals;
	xor: typeof xor;
}
