export * from "./constants.js";
export type BrandedOpcode = import("./OpcodeType.js").OpcodeType;
export const BrandedOpcode: {
    STOP: import("./OpcodeType.js").OpcodeType;
    ADD: import("./OpcodeType.js").OpcodeType;
    MUL: import("./OpcodeType.js").OpcodeType;
    SUB: import("./OpcodeType.js").OpcodeType;
    DIV: import("./OpcodeType.js").OpcodeType;
    SDIV: import("./OpcodeType.js").OpcodeType;
    MOD: import("./OpcodeType.js").OpcodeType;
    SMOD: import("./OpcodeType.js").OpcodeType;
    ADDMOD: import("./OpcodeType.js").OpcodeType;
    MULMOD: import("./OpcodeType.js").OpcodeType;
    EXP: import("./OpcodeType.js").OpcodeType;
    SIGNEXTEND: import("./OpcodeType.js").OpcodeType;
    LT: import("./OpcodeType.js").OpcodeType;
    GT: import("./OpcodeType.js").OpcodeType;
    SLT: import("./OpcodeType.js").OpcodeType;
    SGT: import("./OpcodeType.js").OpcodeType;
    EQ: import("./OpcodeType.js").OpcodeType;
    ISZERO: import("./OpcodeType.js").OpcodeType;
    AND: import("./OpcodeType.js").OpcodeType;
    OR: import("./OpcodeType.js").OpcodeType;
    XOR: import("./OpcodeType.js").OpcodeType;
    NOT: import("./OpcodeType.js").OpcodeType;
    BYTE: import("./OpcodeType.js").OpcodeType;
    SHL: import("./OpcodeType.js").OpcodeType;
    SHR: import("./OpcodeType.js").OpcodeType;
    SAR: import("./OpcodeType.js").OpcodeType;
    KECCAK256: import("./OpcodeType.js").OpcodeType;
    ADDRESS: import("./OpcodeType.js").OpcodeType;
    BALANCE: import("./OpcodeType.js").OpcodeType;
    ORIGIN: import("./OpcodeType.js").OpcodeType;
    CALLER: import("./OpcodeType.js").OpcodeType;
    CALLVALUE: import("./OpcodeType.js").OpcodeType;
    CALLDATALOAD: import("./OpcodeType.js").OpcodeType;
    CALLDATASIZE: import("./OpcodeType.js").OpcodeType;
    CALLDATACOPY: import("./OpcodeType.js").OpcodeType;
    CODESIZE: import("./OpcodeType.js").OpcodeType;
    CODECOPY: import("./OpcodeType.js").OpcodeType;
    GASPRICE: import("./OpcodeType.js").OpcodeType;
    EXTCODESIZE: import("./OpcodeType.js").OpcodeType;
    EXTCODECOPY: import("./OpcodeType.js").OpcodeType;
    RETURNDATASIZE: import("./OpcodeType.js").OpcodeType;
    RETURNDATACOPY: import("./OpcodeType.js").OpcodeType;
    EXTCODEHASH: import("./OpcodeType.js").OpcodeType;
    BLOCKHASH: import("./OpcodeType.js").OpcodeType;
    COINBASE: import("./OpcodeType.js").OpcodeType;
    TIMESTAMP: import("./OpcodeType.js").OpcodeType;
    NUMBER: import("./OpcodeType.js").OpcodeType;
    DIFFICULTY: import("./OpcodeType.js").OpcodeType;
    GASLIMIT: import("./OpcodeType.js").OpcodeType;
    CHAINID: import("./OpcodeType.js").OpcodeType;
    SELFBALANCE: import("./OpcodeType.js").OpcodeType;
    BASEFEE: import("./OpcodeType.js").OpcodeType;
    BLOBHASH: import("./OpcodeType.js").OpcodeType;
    BLOBBASEFEE: import("./OpcodeType.js").OpcodeType;
    POP: import("./OpcodeType.js").OpcodeType;
    MLOAD: import("./OpcodeType.js").OpcodeType;
    MSTORE: import("./OpcodeType.js").OpcodeType;
    MSTORE8: import("./OpcodeType.js").OpcodeType;
    SLOAD: import("./OpcodeType.js").OpcodeType;
    SSTORE: import("./OpcodeType.js").OpcodeType;
    JUMP: import("./OpcodeType.js").OpcodeType;
    JUMPI: import("./OpcodeType.js").OpcodeType;
    PC: import("./OpcodeType.js").OpcodeType;
    MSIZE: import("./OpcodeType.js").OpcodeType;
    GAS: import("./OpcodeType.js").OpcodeType;
    JUMPDEST: import("./OpcodeType.js").OpcodeType;
    TLOAD: import("./OpcodeType.js").OpcodeType;
    TSTORE: import("./OpcodeType.js").OpcodeType;
    MCOPY: import("./OpcodeType.js").OpcodeType;
    PUSH0: import("./OpcodeType.js").OpcodeType;
    PUSH1: import("./OpcodeType.js").OpcodeType;
    PUSH2: import("./OpcodeType.js").OpcodeType;
    PUSH3: import("./OpcodeType.js").OpcodeType;
    PUSH4: import("./OpcodeType.js").OpcodeType;
    PUSH5: import("./OpcodeType.js").OpcodeType;
    PUSH6: import("./OpcodeType.js").OpcodeType;
    PUSH7: import("./OpcodeType.js").OpcodeType;
    PUSH8: import("./OpcodeType.js").OpcodeType;
    PUSH9: import("./OpcodeType.js").OpcodeType;
    PUSH10: import("./OpcodeType.js").OpcodeType;
    PUSH11: import("./OpcodeType.js").OpcodeType;
    PUSH12: import("./OpcodeType.js").OpcodeType;
    PUSH13: import("./OpcodeType.js").OpcodeType;
    PUSH14: import("./OpcodeType.js").OpcodeType;
    PUSH15: import("./OpcodeType.js").OpcodeType;
    PUSH16: import("./OpcodeType.js").OpcodeType;
    PUSH17: import("./OpcodeType.js").OpcodeType;
    PUSH18: import("./OpcodeType.js").OpcodeType;
    PUSH19: import("./OpcodeType.js").OpcodeType;
    PUSH20: import("./OpcodeType.js").OpcodeType;
    PUSH21: import("./OpcodeType.js").OpcodeType;
    PUSH22: import("./OpcodeType.js").OpcodeType;
    PUSH23: import("./OpcodeType.js").OpcodeType;
    PUSH24: import("./OpcodeType.js").OpcodeType;
    PUSH25: import("./OpcodeType.js").OpcodeType;
    PUSH26: import("./OpcodeType.js").OpcodeType;
    PUSH27: import("./OpcodeType.js").OpcodeType;
    PUSH28: import("./OpcodeType.js").OpcodeType;
    PUSH29: import("./OpcodeType.js").OpcodeType;
    PUSH30: import("./OpcodeType.js").OpcodeType;
    PUSH31: import("./OpcodeType.js").OpcodeType;
    PUSH32: import("./OpcodeType.js").OpcodeType;
    DUP1: import("./OpcodeType.js").OpcodeType;
    DUP2: import("./OpcodeType.js").OpcodeType;
    DUP3: import("./OpcodeType.js").OpcodeType;
    DUP4: import("./OpcodeType.js").OpcodeType;
    DUP5: import("./OpcodeType.js").OpcodeType;
    DUP6: import("./OpcodeType.js").OpcodeType;
    DUP7: import("./OpcodeType.js").OpcodeType;
    DUP8: import("./OpcodeType.js").OpcodeType;
    DUP9: import("./OpcodeType.js").OpcodeType;
    DUP10: import("./OpcodeType.js").OpcodeType;
    DUP11: import("./OpcodeType.js").OpcodeType;
    DUP12: import("./OpcodeType.js").OpcodeType;
    DUP13: import("./OpcodeType.js").OpcodeType;
    DUP14: import("./OpcodeType.js").OpcodeType;
    DUP15: import("./OpcodeType.js").OpcodeType;
    DUP16: import("./OpcodeType.js").OpcodeType;
    SWAP1: import("./OpcodeType.js").OpcodeType;
    SWAP2: import("./OpcodeType.js").OpcodeType;
    SWAP3: import("./OpcodeType.js").OpcodeType;
    SWAP4: import("./OpcodeType.js").OpcodeType;
    SWAP5: import("./OpcodeType.js").OpcodeType;
    SWAP6: import("./OpcodeType.js").OpcodeType;
    SWAP7: import("./OpcodeType.js").OpcodeType;
    SWAP8: import("./OpcodeType.js").OpcodeType;
    SWAP9: import("./OpcodeType.js").OpcodeType;
    SWAP10: import("./OpcodeType.js").OpcodeType;
    SWAP11: import("./OpcodeType.js").OpcodeType;
    SWAP12: import("./OpcodeType.js").OpcodeType;
    SWAP13: import("./OpcodeType.js").OpcodeType;
    SWAP14: import("./OpcodeType.js").OpcodeType;
    SWAP15: import("./OpcodeType.js").OpcodeType;
    SWAP16: import("./OpcodeType.js").OpcodeType;
    LOG0: import("./OpcodeType.js").OpcodeType;
    LOG1: import("./OpcodeType.js").OpcodeType;
    LOG2: import("./OpcodeType.js").OpcodeType;
    LOG3: import("./OpcodeType.js").OpcodeType;
    LOG4: import("./OpcodeType.js").OpcodeType;
    CREATE: import("./OpcodeType.js").OpcodeType;
    CALL: import("./OpcodeType.js").OpcodeType;
    CALLCODE: import("./OpcodeType.js").OpcodeType;
    RETURN: import("./OpcodeType.js").OpcodeType;
    DELEGATECALL: import("./OpcodeType.js").OpcodeType;
    CREATE2: import("./OpcodeType.js").OpcodeType;
    AUTH: import("./OpcodeType.js").OpcodeType;
    AUTHCALL: import("./OpcodeType.js").OpcodeType;
    STATICCALL: import("./OpcodeType.js").OpcodeType;
    REVERT: import("./OpcodeType.js").OpcodeType;
    INVALID: import("./OpcodeType.js").OpcodeType;
    SELFDESTRUCT: import("./OpcodeType.js").OpcodeType;
    disassemble: typeof disassemble;
    dupPosition: typeof dupPosition;
    format: typeof format;
    getCategory: typeof getCategory;
    getDescription: typeof getDescription;
    getGasCost: typeof getGasCost;
    getName: typeof getName;
    getPushSize: typeof getPushSize;
    getStackEffect: typeof getStackEffect;
    getStackInput: typeof getStackInput;
    getStackOutput: typeof getStackOutput;
    info: typeof info;
    isDup: typeof isDup;
    isJump: typeof isJump;
    isJumpDestination: typeof isJumpDestination;
    isLog: typeof isLog;
    isPush: typeof isPush;
    isSwap: typeof isSwap;
    isTerminating: typeof isTerminating;
    isTerminator: typeof isTerminator;
    isValid: typeof isValid;
    isValidJumpDest: typeof isValidJumpDest;
    isValidOpcode: typeof isValidOpcode;
    jumpDests: typeof jumpDests;
    logTopics: typeof logTopics;
    name: typeof name;
    parse: typeof parse;
    pushBytes: typeof pushBytes;
    pushOpcode: typeof pushOpcode;
    swapPosition: typeof swapPosition;
};
export type Instruction = import("./OpcodeType.js").Instruction;
export type Info = import("./OpcodeType.js").Info;
import { disassemble } from "./disassemble.js";
import { dupPosition } from "./dupPosition.js";
import { format } from "./format.js";
import { getCategory } from "./getCategory.js";
import { getDescription } from "./getDescription.js";
import { getGasCost } from "./getGasCost.js";
import { getName } from "./getName.js";
import { getPushSize } from "./getPushSize.js";
import { getStackEffect } from "./getStackEffect.js";
import { getStackInput } from "./getStackInput.js";
import { getStackOutput } from "./getStackOutput.js";
import { info } from "./info.js";
import { isDup } from "./isDup.js";
import { isJump } from "./isJump.js";
import { isJumpDestination } from "./isJumpDestination.js";
import { isLog } from "./isLog.js";
import { isPush } from "./isPush.js";
import { isSwap } from "./isSwap.js";
import { isTerminating } from "./isTerminating.js";
import { isTerminator } from "./isTerminator.js";
import { isValid } from "./isValid.js";
import { isValidJumpDest } from "./isValidJumpDest.js";
import { isValidOpcode } from "./isValidOpcode.js";
import { jumpDests } from "./jumpDests.js";
import { logTopics } from "./logTopics.js";
import { name } from "./name.js";
import { parse } from "./parse.js";
import { pushBytes } from "./pushBytes.js";
import { pushOpcode } from "./pushOpcode.js";
import { swapPosition } from "./swapPosition.js";
/**
 * Identity function for type branding
 *
 * @param {number} value - Opcode byte value
 * @returns {BrandedOpcode} Branded opcode
 */
export function Opcode(value: number): BrandedOpcode;
export namespace Opcode {
    export { disassemble };
    export { dupPosition };
    export { format };
    export { getCategory };
    export { getDescription };
    export { getGasCost };
    export { getName };
    export { getPushSize };
    export { getStackEffect };
    export { getStackInput };
    export { getStackOutput };
    export { info };
    export { isDup };
    export { isJump };
    export { isJumpDestination };
    export { isLog };
    export { isPush };
    export { isSwap };
    export { isTerminating };
    export { isTerminator };
    export { isValid };
    export { isValidJumpDest };
    export { isValidOpcode };
    export { jumpDests };
    export { logTopics };
    export let name: typeof import("./name.js").name;
    export { parse };
    export { pushBytes };
    export { pushOpcode };
    export { swapPosition };
}
export { disassemble, dupPosition, format, getCategory, getDescription, getGasCost, getName, getPushSize, getStackEffect, getStackInput, getStackOutput, info, isDup, isJump, isJumpDestination, isLog, isPush, isSwap, isTerminating, isTerminator, isValid, isValidJumpDest, isValidOpcode, jumpDests, logTopics, name, parse, pushBytes, pushOpcode, swapPosition, disassemble as _disassemble, dupPosition as _dupPosition, format as _format, getCategory as _getCategory, getDescription as _getDescription, getGasCost as _getGasCost, getName as _getName, getPushSize as _getPushSize, getStackEffect as _getStackEffect, getStackInput as _getStackInput, getStackOutput as _getStackOutput, info as _info, isDup as _isDup, isJump as _isJump, isJumpDestination as _isJumpDestination, isLog as _isLog, isPush as _isPush, isSwap as _isSwap, isTerminating as _isTerminating, isTerminator as _isTerminator, isValid as _isValid, isValidJumpDest as _isValidJumpDest, isValidOpcode as _isValidOpcode, jumpDests as _jumpDests, logTopics as _logTopics, name as _name, parse as _parse, pushBytes as _pushBytes, pushOpcode as _pushOpcode, swapPosition as _swapPosition };
//# sourceMappingURL=Opcode.d.ts.map